## Variable
== in old version pytorch == <br />
Variable 有自動求導的功能 (autograd) <br />
![](https://pytorch.org/tutorials/_images/Variable.png)

In [3]:
import torch
from torch.autograd import Variable # torch 中 Variable 模块

* Create Variable

In [18]:
x = Variable(torch.Tensor([1]),requires_grad=True)
w = Variable(torch.Tensor([2]),requires_grad=True)
b = Variable(torch.Tensor([3]),requires_grad=True)

#build a computational graph
y = x*w+b
y

tensor([5.], grad_fn=<AddBackward0>)

* Compute Gradient

In [19]:
y.backward()  # same as y.backward(torch.FloatTensor([1]))

print(x.grad) #對x做一階微分
print(w.grad)
print(b.grad)

tensor([2.])
tensor([1.])
tensor([1.])


* Matrix Gradient

In [20]:
x = torch.randn(3)
x = Variable(x,requires_grad=True)

y = x*2
print(x)

tensor([-1.4984,  0.6242, -0.4408], requires_grad=True)


In [21]:
y.backward(torch.FloatTensor([1,0.1,0.01])) #梯度分別乘 1,0.1,0.01
print(x.grad)

tensor([2.0000, 0.2000, 0.0200])
