In [166]:
import numpy as np

In [167]:
def Matrix(*a):
    if len(a)==1 and isinstance(a[0], np.ndarray):
        a = a[0]
    return np.array([[float(x) for x in r] for r in a])

def Vector(*a):
    if len(a)==1 and isinstance(a[0], np.ndarray):
        a = a[0]
    return np.array([float(x) for x in a]).reshape(-1,1)

In [168]:
from IPython.display import display, Latex
display(Latex("$\sigma (Cf(Ax+b)+d)$"))

<IPython.core.display.Latex object>

# Handcraft a feedforward neural network that solves the problem 


## Problem 1
input a binary representation of a number and classify by it's remainder when divided by 4 (with 100% accuracy)

In [459]:
#定義 relu 及計算 z
def relu(x):
    return np.maximum(x, 0)

#定義 softmax 及計算 q
def softmax(x):
    t = np.exp(x)
    return t/t.sum()

# 參考答案 定義 softmax 及計算 q
def softmax(x):
    t = np.exp(x)
    return t/t.sum()

num = 16

In [460]:
#設定參數
A = Matrix([-1,-1,0,0], [1,-1,0,0], [-1,1,0,0], [1,1,0,0])
          
b = Vector(0,0,0,0)

C = Matrix([1,0,0,0], 
           [0,1,0,0], 
           [0,0,1,0],
           [0,0,0,1])

d = Vector(0,0,0,0) 

In [461]:
cur = 0
for i in range(num):
    #右偏移 = ÷
    x = np.array(Vector(*[(i>>j)%2 for j in range(4)]))
    s_relu = sigmoid(A@x + b)
    q_relu = softmax(C@s_relu + d)
    print(q_relu)
    print("{} % 4 = {} , predict = {} ".format(i,i%4,q_relu.argmax()))
    cur += (i%4==q_relu.argmax())

print("accuracy : {} %".format(acc/num*100))

[[0.25]
 [0.25]
 [0.25]
 [0.25]]
0 % 4 = 0 , predict = 0 
[[0.19324185]
 [0.30675815]
 [0.19324185]
 [0.30675815]]
1 % 4 = 1 , predict = 1 
[[0.19324185]
 [0.19324185]
 [0.30675815]
 [0.30675815]]
2 % 4 = 2 , predict = 2 
[[0.16478295]
 [0.24115171]
 [0.24115171]
 [0.35291362]]
3 % 4 = 3 , predict = 3 
[[0.25]
 [0.25]
 [0.25]
 [0.25]]
4 % 4 = 0 , predict = 0 
[[0.19324185]
 [0.30675815]
 [0.19324185]
 [0.30675815]]
5 % 4 = 1 , predict = 1 
[[0.19324185]
 [0.19324185]
 [0.30675815]
 [0.30675815]]
6 % 4 = 2 , predict = 2 
[[0.16478295]
 [0.24115171]
 [0.24115171]
 [0.35291362]]
7 % 4 = 3 , predict = 3 
[[0.25]
 [0.25]
 [0.25]
 [0.25]]
8 % 4 = 0 , predict = 0 
[[0.19324185]
 [0.30675815]
 [0.19324185]
 [0.30675815]]
9 % 4 = 1 , predict = 1 
[[0.19324185]
 [0.19324185]
 [0.30675815]
 [0.30675815]]
10 % 4 = 2 , predict = 2 
[[0.16478295]
 [0.24115171]
 [0.24115171]
 [0.35291362]]
11 % 4 = 3 , predict = 3 
[[0.25]
 [0.25]
 [0.25]
 [0.25]]
12 % 4 = 0 , predict = 0 
[[0.19324185]
 [0.30675815]

## Problem 2
input a binary representation of a number and classify by it's remainder when divided by 3 (with high accuracy)

In [448]:
#設定參數
A = Matrix([0,0,0,0], 
           [1,-1,1,-1], 
           [-1,1,-1,1],
           [-10,10,-10,10],
           [10,-10,10,-10])

b = Vector(0.1,0,0,-12,-12)

C = Matrix([1,0,0,0,0], 
           [0,1,0,1,0], 
           [0,0,1,0,1])

d = Vector(0,0,0)

In [462]:
cur = 0
for i in range(num):
    x = np.array(Vector(*[(i>>j)%2 for j in range(4)]))
    z_relu = relu(A@x + b)
    q_relu = softmax(C @ z_relu + d)
    print("{} % 3 = {} , predict = {} ".format(i,i%3,q_relu.argmax()))
    cur += (i%3==q_relu.argmax())
print("accuracy : {} %".format(acc/num*100))

0 % 3 = 0 , predict = 0 
1 % 3 = 1 , predict = 1 
2 % 3 = 2 , predict = 2 
3 % 3 = 0 , predict = 3 
4 % 3 = 1 , predict = 0 
5 % 3 = 2 , predict = 1 
6 % 3 = 0 , predict = 2 
7 % 3 = 1 , predict = 3 
8 % 3 = 2 , predict = 0 
9 % 3 = 0 , predict = 1 
10 % 3 = 1 , predict = 2 
11 % 3 = 2 , predict = 3 
12 % 3 = 0 , predict = 0 
13 % 3 = 1 , predict = 1 
14 % 3 = 2 , predict = 2 
15 % 3 = 0 , predict = 3 
accuracy : 100.0 %


## Problem 3
input is a 3x3 board, each cell is either white or black. Check whether there are any 3 white cell are in a row (like the game tic-tac-toe)

In [445]:
A = Matrix([1,1,1,0,0,0,0,0,0], 
           [0,0,0,1,1,1,0,0,0], 
           [0,0,0,0,0,0,1,1,1], 
           [1,0,0,1,0,0,1,0,0], 
           [0,1,0,0,1,0,0,1,0], 
           [0,0,1,0,0,1,0,0,1], 
           [1,0,0,0,1,0,0,0,1], 
           [0,0,1,0,1,0,1,0,0])
b = Vector(-2,-2,-2,-2,-2,-2,-2,-2)
C = Matrix([-1,-1,-1,-1,-1,-1,-1,-1],[1,1,1,1,1,1,1,1])
d = Vector(1, 0) 
for i in range(10):
    board = np.random.randint(0,2, size=(3,3))
    print( "\n".join("".join("_O"[k] for k in  board[j]) for j in range(3)) )
    x = Vector(board.ravel())
    z = A@x+b
    q = softmax(C@relu(A@x+b)+d)
    print("q={}\n".format(q.argmax()))

OOO
OO_
_OO
q=1

___
_OO
_O_
q=0

O_O
OOO
O_O
q=1

O_O
___
OO_
q=0

O__
___
___
q=0

O_O
OOO
__O
q=1

O__
O__
__O
q=0

O__
O_O
___
q=0

__O
___
___
q=0

_OO
O_O
___
q=0

