Feedforward Network practice
re:https://github.com/tjwei/CrashCourseML/blob/master/DIY_NN/01-FeedForward-Forward%20Propagation.ipynb

In [1]:
import numpy as np

In [22]:
%run magic.ipynb
# or copy paste the cell from https://github.com/tjwei/CrashCourseML/blob/master/DIY_NN/magic.ipynb

In [21]:
from IPython.display import display, Latex
display(Latex("$\sigma (Cf(Ax+b)+d)$"))

<IPython.core.display.Latex object>

In [8]:
#請在這裡計算
np.random.seed(1234)

In [23]:
# 參考答案，設定權重
#%run -i solutions/ff_init_variables.py
A = np.random.randint(-2,3,size=(6,4))
b = np.random.randint(-2,3,size=(6))
C = np.random.randint(-2,3,size=(3,6))
d = np.random.randint(-2,3,size=(3))
x = np.random.randint(-2,3,size=(4))
display(A)
display(b)
display(C)
display(d)
display(x)

array([[ 1,  2,  2, -2],
       [-1, -1, -1,  0],
       [ 1,  2,  2,  0],
       [ 0, -2, -2,  2],
       [-2, -1,  0, -2],
       [ 1,  2,  0,  0]])

array([ 1,  1, -2, -1,  1, -2])

array([[ 1,  0,  1,  2, -1,  1],
       [ 1,  1,  0, -1,  1,  2],
       [ 0,  1,  2, -1,  2, -2]])

array([ 2, -1, -1])

array([ 2, -1,  2, -2])

In [26]:
# 參考答案 定義 relu, sigmoid 及計算 z
# %run -i solutions/ff_compute_z.py
def relu(x):
    return np.maximum(x, 0)
def sigmoid(x):
    return 1/(1+np.exp(-x))
z_relu = relu(A@x + b)
z_sigmoid = sigmoid(A@x + b )
display(z_relu)
display(z_sigmoid)

array([9, 0, 2, 0, 2, 0])

array([9.99876605e-01, 1.19202922e-01, 8.80797078e-01, 9.11051194e-04,
       8.80797078e-01, 1.19202922e-01])

In [28]:
# 參考答案 定義 softmax 及計算 q
# %run -i solutions/ff_compute_q.py
def softmax(x):
    t = np.exp(x)
    return t/t.sum()
q_relu = softmax(C @ relu(A @ x + b) + d)
q_sigmoid = softmax(C @ sigmoid(A @ x + b) + d)

display(q_relu)
display(q_sigmoid)

array([0.72139918, 0.26538793, 0.01321289])

array([0.60980691, 0.09272259, 0.2974705 ])

### 練習
設計一個網路:<br />
<br />
    。輸入是二進位 0 ~ 15<br />
    。輸出依照對於 3 的餘數分成三類

In [32]:
# Hint 下面產生數字 i 的 2 進位向量
i = 13
x = np.array(Vector(*[(i>>j)%2 for j in range(4)]))
x

array([[1.],
       [0.],
       [1.],
       [1.]])

In [46]:
# 參考解答
# %run -i solutions/ff_mod3.py
A = Matrix([0,0,0,0], 
           [1,-1,1,-1], 
           [-1,1,-1,1],
           [-10,10,-10,10],
           [10,-10,10,-10],
          )
b = Vector(0.1,0,0,-12,-12)

C = Matrix([1,0,0,0,0], 
           [0,1,0,1,0], 
           [0,0,1,0,1],
          )
d = Vector(0,0,0) 
acc = 0
for i in range(16):
    x = np.array(Vector(*[(i>>j)%2 for j in range(4)]))
    q = softmax(C@relu(A@x+b)+d)
    print("i={}, i%3={}, q={}".format(i, i%3, q.argmax()))
    acc += (i%3==q.argmax())
print("accuracy : {} %".format(acc/16*100))

i=0, i%3=0, q=0
i=1, i%3=1, q=1
i=2, i%3=2, q=2
i=3, i%3=0, q=0
i=4, i%3=1, q=1
i=5, i%3=2, q=2
i=6, i%3=0, q=0
i=7, i%3=1, q=1
i=8, i%3=2, q=2
i=9, i%3=0, q=0
i=10, i%3=1, q=1
i=11, i%3=2, q=2
i=12, i%3=0, q=0
i=13, i%3=1, q=1
i=14, i%3=2, q=2
i=15, i%3=0, q=0
accuracy : 100.0 %


### 練習
設計一個網路來判斷井字棋是否有連成直線(只需要判斷其中一方即可):

    。輸入是 9 維向量，0 代表空格，1 代表有下子
    。輸出是二維(softmax)或一維(sigmoid)皆可，用來代表 True, False
有連線的例子<br />
_X_ <br />
X__<br />
XXX<br />
<br />
XXX<br />
XX_<br />
_XX<br />
<br />
__X<br />
_XX<br />
X__<br />
沒連線的例子<br />
<br />
XX_<br />
X__<br />
_XX<br />
<br />
_X_<br />
XX_<br />
X_X<br />
<br />
__X<br />
_XX<br />
_X_<br />
<br />


In [42]:
#參考答案
#%run -i solutions/ff_tic_tac_toe.py
A = Matrix([1,1,1,0,0,0,0,0,0], 
           [0,0,0,1,1,1,0,0,0], 
           [0,0,0,0,0,0,1,1,1], 
           [1,0,0,1,0,0,1,0,0], 
           [0,1,0,0,1,0,0,1,0], 
           [0,0,1,0,0,1,0,0,1], 
           [1,0,0,0,1,0,0,0,1], 
           [0,0,1,0,1,0,1,0,0])
b = Vector(-2,-2,-2,-2,-2,-2,-2,-2)
C = Matrix([-1,-1,-1,-1,-1,-1,-1,-1],[1,1,1,1,1,1,1,1])
d = Vector(1, 0) 
for i in range(10):
    board = np.random.randint(0,2, size=(3,3))
    print( "\n".join("".join("_X"[k] for k in  board[j]) for j in range(3)) )
    x = Vector(board.ravel())
    z = A@x+b
    q = softmax(C@relu(A@x+b)+d)
    print("q={}\n".format(q.argmax()))

X__
XX_
__X
q=1

__X
X__
XX_
q=0

_XX
__X
X_X
q=1

__X
XX_
_XX
q=0

X__
_XX
__X
q=1

XX_
XXX
XXX
q=1

__X
_XX
_XX
q=1

___
X_X
___
q=0

__X
XXX
X_X
q=1

XXX
_XX
XXX
q=1

