In [33]:
import numpy as np
from PIL import Image

In [34]:
import os
import urllib
from urllib.request import urlretrieve
dataset = 'mnist.pkl.gz'

#顯示下載進度
def reporthook(a,b,c):
    print("\rdownloading: %5.1f%%"%(a*b*100.0/c), end="")

#檢查是否有dataset，若無則到以下網址下載
if not os.path.isfile(dataset):
        origin = "https://github.com/mnielsen/neural-networks-and-deep-learning/raw/master/data/mnist.pkl.gz"
        print('Downloading data from %s' % origin)
        urlretrieve(origin, dataset, reporthook=reporthook)


In [35]:
import gzip
import pickle

#使用with作open，可以限制f只在with中使用，程式離開with即f.close()
with gzip.open(dataset,'rb') as f :
    train_set, validation_set, test_set = pickle.load(f,encoding='latin1')

train_set
    

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([5, 0, 4, ..., 8, 4, 8]))

In [36]:
%run -i q_see_mnist_data.py
# or use scipy.stats.describe

train_set[0]:      shape=(50000, 784)	 dtype=float32
train_set[1]:      shape=(50000,)	 dtype=int64
validation_set[0]: shape=(10000, 784)	 dtype=float32
validation_set[1]: shape=(10000,)	 dtype=int64
test_set[0]:       shape=(10000, 784)	 dtype=float32
test_set[1]:       shape=(10000,)	 dtype=int64


In [37]:
#切分資料與預測
train_X, train_y = train_set 
#train_X = train_set[0]  train_set = train_set[1]
test_X, test_y = test_set

In [38]:
#查看MNIST的y前20筆
print(train_y[:20])

[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]


In [7]:
#練習查看單一筆資料與印出
print("inital x[1] data")
print(train_X[:1])
print("len(x[1]):",train_X[:1].shape[1]) #每一筆X是長度784的array

#將數值乘上255倍 #clip(0,255)->取0~255之間的整數 
try_X = (train_X[:1]*255).clip(0,255).astype('uint8') 
print("value*255:")
print(try_X)

#將這784個數字轉為每28個為一組，共28組
#print(try_x.reshape(-1,28,28))
print("轉換資料的格式：每28個數字一組共28組 -->28個數字為圖片的一小塊?")
try_X_reshape = try_X.reshape(-1,28,28).swapaxes(0,1).reshape(28,-1)
print(try_X_reshape)

#將此陣列轉成圖形輸出
display(Image.fromarray(try_X_reshape))

inital x[1] data
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        

In [39]:
#查看MNIST的x前20筆
from IPython.display import display 
def showX(X):
    int_X = (X*255).clip(0,255).astype('uint8')
    # N*784 -> N*28*28 -> 28*N*28 -> 28 * 28N
    int_X_reshape = int_X.reshape(-1,28,28).swapaxes(0,1).reshape(28,-1)
    display(Image.fromarray(int_X_reshape))
# 訓練資料， X 的前 20 筆
showX(train_X[:20])

In [40]:
%run -i q_square_error.py

86.94919
86.949183020698


In [41]:
%run -i q_find_nn_0.py

train_X[38620]


train_X[38620] = 7
test_y[0] = 7


In [42]:
%run -i q_find_nn_10.py


test_X[0]


train_X[38620]


train_X[38620] = 7
train_X[0] = 7
test_X[1]


train_X[28882]


train_X[28882] = 2
train_X[1] = 2
test_X[2]


train_X[46512]


train_X[46512] = 1
train_X[2] = 1
test_X[3]


train_X[29044]


train_X[29044] = 0
train_X[3] = 0
test_X[4]


train_X[40094]


train_X[40094] = 4
train_X[4] = 4
test_X[5]


train_X[30809]


train_X[30809] = 1
train_X[5] = 1
test_X[6]


train_X[18279]


train_X[18279] = 4
train_X[6] = 4
test_X[7]


train_X[41982]


train_X[41982] = 9
train_X[7] = 9
test_X[8]


train_X[35628]


train_X[35628] = 5
train_X[8] = 5
test_X[9]


train_X[5044]


train_X[5044] = 9
train_X[9] = 9
Accuracy 1.0


In [ ]:
#使用其他方法來計算「相近」

In [52]:
#先將資料 normalize
train_X  = train_X / np.linalg.norm(train_X, axis=1, keepdims=True)
test_X  = test_X / np.linalg.norm(test_X, axis=1, keepdims=True)

In [53]:
# 矩陣乘法 == 大量計算內積
A = test_X @ train_X.T
print(A.shape)

(10000, 50000)


In [54]:
A.argmax(axis=1)

array([44566, 28882, 15224, ...,  3261,  1311, 22424])

In [55]:
train_y[44566]

7

In [56]:
predict_y = train_y[A.argmax(axis=1)]

In [57]:
# 測試資料， X 的前 20 筆
showX(test_set[0][:20])

In [58]:
# 猜測的 Y 前20筆
predict_y[:20]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4])

In [59]:
#測試資料的 y 前 20 筆
test_y[:20]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4])

In [60]:
# 正確率
print((predict_y == test_y).mean()*100,'%')

97.08 %


In [67]:
#使用PCA來降低資料維度
from sklearn.decomposition import PCA
pca = PCA(n_components=50)
train_X = pca.fit_transform(train_set[0])
test_X = pca.transform(test_set[0])
train_X.shape

(50000, 50)

In [68]:
train_X /= np.linalg.norm(train_X, axis=1, keepdims=True)
test_X /= np.linalg.norm(test_X, axis=1, keepdims=True)

# 矩陣乘法
A = test_X @ train_X.T
predict_y = train_y[A.argmax(axis=1)]
# 正確率
print((predict_y == test_y).mean()*100,'%')


97.11 %
