Softmax practice
re:https://github.com/tjwei/CrashCourseML/blob/master/DIY_NN/Softmax.ipynb

In [2]:
import numpy as np

先隨便算一個R^2 -> R^3 的網路

In [3]:
%run magic.ipynb

In [4]:
#Weight
W = Matrix([1,2],[3,4],[5,6])
W

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [5]:
#Bias
b = Vector(1,0,-1)
b

array([[ 1.],
       [ 0.],
       [-1.]])

In [6]:
# Input
x = Vector(2,-1)
x

array([[ 2.],
       [-1.]])

## 任務：計算最後的猜測機率q

In [7]:
# %load solutions/softmax_compute_q.py
#參考答案：https://github.com/tjwei/CrashCourseML/blob/master/DIY_NN/solutions/softmax_compute_q.py

# Wx+b
c = W @ x + b

# d = exp(Wx+b)
d = np.exp(c)

# q = d/sum(d)
q = d/d.sum()

q

array([[0.09003057],
       [0.24472847],
       [0.66524096]])

### 練習：
設計一個網路
    。輸入是二進位 0~15
    。輸出依照對於4的餘數分成四類
Hint : 可以參考上面 w , b的設定方式

In [8]:
i = 13
#轉為2進位
x = Vector(i%2,(i>>1)%2,(i>>2)%2,(i>>3)%2)
x #1011

array([[1.],
       [0.],
       [1.],
       [1.]])

In [10]:
#計算
W = Matrix([-1,-1,0,0], [1,-1,0,0], [-1,1,0,0], [1,1,0,0])
b = Vector(0,0,0,0)
for i in range(16):
    x = Vector(i%2, (i>>1)%2, (i>>2)%2, (i>>3)%2)
    r = W @ x + b
    print("i=", i, "predict:", r.argmax(), "ground truth:", i%4)

#參考答案：https://github.com/tjwei/CrashCourseML/blob/master/DIY_NN/solutions/softmax_mod4.py

i= 0 predict: 0 ground truth: 0
i= 1 predict: 1 ground truth: 1
i= 2 predict: 2 ground truth: 2
i= 3 predict: 3 ground truth: 3
i= 4 predict: 0 ground truth: 0
i= 5 predict: 1 ground truth: 1
i= 6 predict: 2 ground truth: 2
i= 7 predict: 3 ground truth: 3
i= 8 predict: 0 ground truth: 0
i= 9 predict: 1 ground truth: 1
i= 10 predict: 2 ground truth: 2
i= 11 predict: 3 ground truth: 3
i= 12 predict: 0 ground truth: 0
i= 13 predict: 1 ground truth: 1
i= 14 predict: 2 ground truth: 2
i= 15 predict: 3 ground truth: 3


# Gradient descent 誤差函數
為了要評斷我們的預測的品質，要設計一個評斷誤差的方式 <br /> 
假設輸入值x對應到的真實類別是y，那我們定義誤差函數 <br />
使用<b>Cross Entropy</b>
 

In [29]:
#先產生隨機的 W / B
W = Matrix(np.random.normal(size=(3,4)))
print(W)
b = Vector(np.random.normal(size=(3,)))
print(b)

[[-1.4932432   0.72711632  0.90136378  0.5354255 ]
 [-0.32162684  0.19246346  0.23251444 -1.46401507]
 [-1.09724217  0.14083738 -0.05904267 -0.22846953]]
[[-0.21257254]
 [ 0.83733359]
 [-0.22814961]]


### 問題：w/b的size為什麼要這樣設定？

### 任務：隨便設定一組x,y 跑跑看Gradient descent

In [78]:
i = 14
x = Vector(i%2, (i>>1)%2, (i>>2)%2, (i>>3)%2)
y = i%3
y

2

### 步驟：計算q

In [79]:
# Wx+b
c = W @ x + b

# d = exp(Wx+b)
d = np.exp(c)

# q = d/sum(d)
q = d/d.sum()
q

array([[0.37106728],
       [0.18571493],
       [0.44321778]])

### 步驟：計算loss

In [80]:
loss = -np.log(q[y])
loss

array([0.81369402])

### 步驟：計算對b的gradient

In [83]:
grad_b = q.copy()
grad_b[y] -= 1
grad_b

array([[ 0.37106728],
       [ 0.18571493],
       [-0.55678222]])

### 步驟：計算對W的gradient

In [86]:
grad_W =   q @ x.T
print(grad_W)
print(grad_W[y])
print(x)
grad_W[y] -= x.ravel()
print(grad_W[y])

# or 
grad_W = grad_b @ x.T
grad_W

[[0.         0.37106728 0.37106728 0.37106728]
 [0.         0.18571493 0.18571493 0.18571493]
 [0.         0.44321778 0.44321778 0.44321778]]
[0.         0.44321778 0.44321778 0.44321778]
[[0.]
 [1.]
 [1.]
 [1.]]
[ 0.         -0.55678222 -0.55678222 -0.55678222]


array([[ 0.        ,  0.37106728,  0.37106728,  0.37106728],
       [ 0.        ,  0.18571493,  0.18571493,  0.18571493],
       [ 0.        , -0.55678222, -0.55678222, -0.55678222]])

### 步驟：更新W,b 個減掉0.5*gradient，然後看看新的loss是否有進步了

In [54]:
W -= 0.5 * grad_W
b -= 0.5 * grad_b

In [55]:
print("原先的q")
q

原先的q


array([[0.00930648],
       [0.01989374],
       [0.97079977]])

In [56]:
print("原先的loss")
loss

原先的loss


array([0.02963504])

In [57]:
# Wx+b
c = W @ x + b
# d = exp(Wx+b)
d = np.exp(c)
# q = d/sum(d)
q = d/d.sum()
print("更新後的q")
q

更新後的q


array([[0.0086387 ],
       [0.01807936],
       [0.97328195]])

In [58]:
loss = -np.log(q[y])
loss
print("更新後的loss")
loss

更新後的loss


array([0.02708147])

# 一次訓練多組資料

上面只針對一組 x (i=14)來訓練，如果一次對所有x做訓練 <br />
通常我們會把組別放在 axis=0

In [92]:
X = np.array([Vector(i%2,(i>>1)%2,(i>>2)%2,(i>>3)%2) for i in range(16)])

In [93]:
for i in range(5):
    print("i=",i)
    display(X[i])

i= 0


array([[0.],
       [0.],
       [0.],
       [0.]])

i= 1


array([[1.],
       [0.],
       [0.],
       [0.]])

i= 2


array([[0.],
       [1.],
       [0.],
       [0.]])

i= 3


array([[1.],
       [1.],
       [0.],
       [0.]])

i= 4


array([[0.],
       [0.],
       [1.],
       [0.]])

In [94]:
# 對應的組別
y = np.array([i%3 for i in range(16)])
y

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0])

### 任務：將訓練向量化

In [95]:
d = np.exp(W@X+b)
q = d/d.sum(axis=(1,2),keepdims=True)
q

array([[[0.40446299],
        [0.31131314],
        [0.28422387]],

       [[0.35126712],
        [0.43410835],
        [0.21462453]],

       [[0.33732402],
        [0.17446661],
        [0.48820937]],

       [[0.32374631],
        [0.26885112],
        [0.40740257]],

       [[0.35321005],
        [0.43277826],
        [0.21401169]],

       [[0.28619347],
        [0.56303329],
        [0.15077324]],

       [[0.32560095],
        [0.26808   ],
        [0.40631905]],

       [[0.29351361],
        [0.38801541],
        [0.31847098]],

       [[0.34643136],
        [0.18626206],
        [0.46730657]],

       [[0.32936652],
        [0.28433389],
        [0.38629958]],

       [[0.24157642],
        [0.08727867],
        [0.67114491]],

       [[0.25027075],
        [0.14517962],
        [0.60454963]],

       [[0.33123881],
        [0.28350592],
        [0.38525527]],

       [[0.29537632],
        [0.40591824],
        [0.29870545]],

       [[0.2518532 ],
        [0.14484875],
    

In [96]:
loss = -np.log(q[y])
loss

array([[[0.90519504],
        [1.16695598],
        [1.25799308]],

       [[1.04620832],
        [0.83446112],
        [1.53886515]],

       [[1.08671132],
        [1.74602192],
        [0.71701093]],

       [[0.90519504],
        [1.16695598],
        [1.25799308]],

       [[1.04620832],
        [0.83446112],
        [1.53886515]],

       [[1.08671132],
        [1.74602192],
        [0.71701093]],

       [[0.90519504],
        [1.16695598],
        [1.25799308]],

       [[1.04620832],
        [0.83446112],
        [1.53886515]],

       [[1.08671132],
        [1.74602192],
        [0.71701093]],

       [[0.90519504],
        [1.16695598],
        [1.25799308]],

       [[1.04620832],
        [0.83446112],
        [1.53886515]],

       [[1.08671132],
        [1.74602192],
        [0.71701093]],

       [[0.90519504],
        [1.16695598],
        [1.25799308]],

       [[1.04620832],
        [0.83446112],
        [1.53886515]],

       [[1.08671132],
        [1.74602192],
    

In [97]:
#用平均當我們的loss
loss.mean()

1.1422345512581762

In [98]:
# fancy indexing :p
one_y = np.eye(3)[y][..., None]
grad_b_all = q - one_y
grad_b = grad_b_all.mean(axis=0)
grad_b

array([[-0.06430979],
       [-0.02447032],
       [ 0.08878011]])

In [99]:
grad_W_all = grad_b_all @ X.swapaxes(1,2)
grad_W = grad_W_all.mean(axis=0)
grad_W

array([[-0.0387909 , -0.04540646, -0.03833764, -0.0440172 ],
       [-0.01750366, -0.01829865, -0.01770741, -0.01451071],
       [ 0.05629457,  0.0637051 ,  0.05604505,  0.05852791]])

In [100]:
W -=  0.5 * grad_W
b -=  0.5 * grad_b

In [101]:
# 之前的 loss
loss.mean()

1.1422345512581762

In [102]:
d = np.exp(W @ X + b)
q = d/d.sum(axis=(1,2), keepdims=True)
loss = -np.log(q[range(len(y)), y])
loss.mean()

1.054335231335711

## 任務：全部合在一起
    。設定W,b
    。設定X
    。訓練30次
        > 計算q / loss
        > 計算 grad_b / grad_W
        > 更新 W / b
    。看看更新後的準確度

In [76]:
# 參考答案：https://github.com/tjwei/CrashCourseML/blob/master/DIY_NN/solutions/softmax_train.py
W = Matrix(np.random.normal(size=(3,4)))
b = Vector(np.random.normal(size=(3,)))
X = np.array([Vector(*[(i>>j)%2 for j in range(4)]) for i in range(16)])
y = np.array([i%3 for i in range(16)])
one_y = np.eye(3)[y][..., None]
print(one_y)
# 紀錄 loss
loss_history = []
for epoch in range(50):
    d = np.exp(W @ X + b)
    q = d/d.sum(axis=(1,2), keepdims=True)
    loss = -np.log(q[range(len(y)), y]).mean()
    loss_history.append(loss)
    accuracy = (q.argmax(axis=1).ravel() == y).mean()
    print(epoch, accuracy)
    grad_b_all = q - one_y
    grad_b = grad_b_all.mean(axis=0)
    grad_W_all = grad_b_all @ X.swapaxes(1,2)
    grad_W = grad_W_all.mean(axis=0)
    W -=  grad_W
    b -= grad_b

[[[1.]
  [0.]
  [0.]]

 [[0.]
  [1.]
  [0.]]

 [[0.]
  [0.]
  [1.]]

 [[1.]
  [0.]
  [0.]]

 [[0.]
  [1.]
  [0.]]

 [[0.]
  [0.]
  [1.]]

 [[1.]
  [0.]
  [0.]]

 [[0.]
  [1.]
  [0.]]

 [[0.]
  [0.]
  [1.]]

 [[1.]
  [0.]
  [0.]]

 [[0.]
  [1.]
  [0.]]

 [[0.]
  [0.]
  [1.]]

 [[1.]
  [0.]
  [0.]]

 [[0.]
  [1.]
  [0.]]

 [[0.]
  [0.]
  [1.]]

 [[1.]
  [0.]
  [0.]]]
0 0.375
1 0.4375
2 0.375
3 0.375
4 0.375
5 0.375
6 0.375
7 0.375
8 0.3125
9 0.3125
10 0.3125
11 0.3125
12 0.3125
13 0.375
14 0.375
15 0.375
16 0.4375
17 0.4375
18 0.4375
19 0.5
20 0.5625
21 0.6875
22 0.6875
23 0.75
24 0.75
25 0.75
26 0.75
27 0.8125
28 0.8125
29 0.8125
30 0.8125
31 0.8125
32 0.8125
33 0.8125
34 0.8125
35 0.8125
36 0.8125
37 0.8125
38 0.8125
39 0.8125
40 0.8125
41 0.8125
42 0.875
43 0.875
44 0.875
45 0.875
46 0.875
47 0.875
48 0.875
49 0.875
